### ISSUE TITLE
Depiction of the payment option in the purchasing UI

### ISSUE THREAD

**Issue by jpitts** [esPass/pretix-eth-payment-plugin#10]
When the user is presented with options to pay, the pretix-eth-payment-plugin displays "Ethereum Plugin". 

![image](https://user-images.githubusercontent.com/509756/60137992-97709000-975d-11e9-90b6-4a351ff3d6c4.png)

I do not see where this can be changed in the Admin Settings for the plugin so it must be what is defined here in payment.py:

https://github.com/esPass/pretix-eth-payment-plugin/blob/1f7764601aceb83643c92619fbc88b349489ce39/pretix_eth/payment.py

I am thinking that it should read: "ETH or DAI" or perhaps "Pay directly with ETH or DAI".

Let me know if there is any impact of changing this to something more comprehensible to a purchasing user.

**Comment by ligi** [comment]
:+1: should be a simple copy change

**Comment by ligi** [comment]
It is now better
