### ISSUE TITLE
Add input validation to the ETH address input

### ISSUE THREAD

**Issue by skylarweaver** [esPass/pretix-eth-payment-plugin#101]
We want to ensure the user is inputting the correct thing: an Ethereum wallet address.

Let's add some sort of validation to the input to ensure only ETH Addresses can be inputted.

https://ethereum.stackexchange.com/questions/1374/how-can-i-check-if-an-ethereum-address-is-valid

https://www.regextester.com/99711

@ligi what is better: the web3 isAddress method or the checksum method? I don't totally understand the checksum method...

**Comment by skylarweaver** [comment]
I've just realized another things: do we accept ENS addresses? I would assume yet, but how can we validate that the input is a valid ETH address _or_ a valid ENS address? @ligi any ideas?

**Comment by ligi** [comment]
> @ligi what is better: the web3 isAddress method or the checksum method? I don't totally understand the checksum method...

as we use the web3 library anyway we can use the isAddress method. This one is also doing a ERC55 checksum check in case of mixed case

> I've just realized another things: do we accept ENS addresses? I would assume yes, but how can we validate that the input is a valid ETH address or a valid ENS address? @ligi any ideas?

if it ends with ".eth", ".xyz", ".luxe", ".art", ".kred" or ".club" -> ens address
else -> hex address

**Comment by skylarweaver** [comment]
We should add validation to ensure each address is unique in the case of multiple ticket purchase. We cannot send two NFTs to the same address, while using Unlock NFTs.

Validation needed per input:
- Ensure HEX eth address or ENS eth address
- Ensure address is unique from all other entered addresses

**Comment by kvbik** [comment]
quick dev note> since we already know we cannot add question type via Pretix plugin, I doubt we can add backend validation of the user data (given how Django forms work). I will check more in depth. In the meantime, we have to stick with web3.js FE validation.

**Comment by ligi** [comment]
no more address collection
