### ISSUE TITLE
Refine provider list

### ISSUE THREAD

**Issue by skylarweaver** [esPass/pretix-eth-payment-plugin#103]
Currently Metamask and WalletConnect. Good start.

@ligi you mentioned burner wallets. I'm not sure that's what we want since this NFT should be eternal and those are ephemeral, right?

Should we also include Ledger and Trezor wallets?
https://www.npmjs.com/package/@web3connect/trezor-provider
https://www.npmjs.com/package/@web3connect/ledger-provider

Gnosis safe uses those providers
<img width="1440" alt="Screen Shot 2020-05-03 at 12 32 24 PM" src="https://user-images.githubusercontent.com/4008777/80913170-7b089100-8d3a-11ea-8ebb-04fc5a72b3c3.png">

Any others? Probably unnecessary...

**Comment by ligi** [comment]
> @ligi you mentioned burner wallets. I'm not sure that's what we want since this NFT should be eternal and those are ephemeral, right?

I rather thought the opposite as I think these NFTs should be used for experiments at the venue or before the event - so be as easily accessible as possible. People can then still move them to a eternal store later on anyway. But to have all options open we could also add trezor and ledger
