### ISSUE TITLE
ETH Payment Plugin charges 7.14 ETH instead of $7.14 in ETH

### ISSUE THREAD

**Issue by skylarweaver** [esPass/pretix-eth-payment-plugin#104]
I'm on this page, I owe 7.14 Euros:
![image](https://user-images.githubusercontent.com/4008777/81132609-0d688a80-8f1d-11ea-8448-d7be5897e56c.png)

I click on Web3Modal, it asks me to pay 7.14 ETH:
![image](https://user-images.githubusercontent.com/4008777/81132634-207b5a80-8f1d-11ea-822f-fd87dae6caf2.png)

I click on Uniswap, same story:
![image](https://user-images.githubusercontent.com/4008777/81132645-296c2c00-8f1d-11ea-8ce2-299f6371a1f6.png)

**Comment by ligi** [comment]
this was a configuration problem - not a problem of the code - closing
