### ISSUE TITLE
CSP error when in WalletConnect flow

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#109]
![Selection_499](https://user-images.githubusercontent.com/111600/81524289-e365fc80-9350-11ea-87d7-6e4cb346037a.png)

**Comment by skylarweaver** [comment]
New error:
![image](https://user-images.githubusercontent.com/4008777/81824637-b4dc5300-9503-11ea-84d9-73fd19c118d1.png)

**Comment by kvbik** [comment]
thx @pauljickling - seems this is fixed!
