### ISSUE TITLE
update/add tests for the new `confirm_payments` command.

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#120]
This should involve adding some test payments at known addresses on Goerli or some other test net and then updating the tests to check for those payments.

extracted from #117

**Comment by Nurts** [comment]
Hi, @ligi I am working on this issue. I was wondering where can I get these known addresses on Goerli?

**Comment by ligi** [comment]
I think just any address - copied the text from https://github.com/esPass/pretix-eth-payment-plugin/issues/122 to not forget about this.
Let's just leave this issue out for now.
I think it is better to continue here: https://github.com/efdevcon/pretix-attestation-placeholder-plugin/milestone/1
