### ISSUE TITLE
Add Refund functionality

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#121]
especially due to covid we should have a refund option

* The plugin should signal it supports refunds ( via BasePaymentProvider.payment_refund_supported) 

* The plugin should provide a file (e.g. csv) with a list of all outstanding refunds (chain, amount, token, value)

* the plugin should check for processed refunds and mark them as paid (not anymore outstanding in previous step)

* the plugin should signal when there is a new outstanding refund (e.g. via email)

**Comment by ayanginet** [comment]
Hey, @ligi, @pipermerriam I was looking into this issue, so far everything seems clear except the third step. I assume that this step involves the implementation of another management command like confirm_payment.py?

**Comment by ayanginet** [comment]
I was working on this issue and it became too large to fit in one PR. So I decided to split it into several PRs and also document what I have done.
1. First PR. Just implement a signal that the plugin supports automatic refunds. Also, add function execute_refund() to store refund related data (wallet, amount, currency).
2. Second PR. Make a [data exporter](https://github.com/pretix/pretix/blob/9fee2d0fbcd42282a4fbab1d79dd2c0e2170dd44/doc/development/api/exporter.rst) for all ethereum related payments and refunds. Currently, there is a way to export payment data as csv, xlsx, but it does not have information like wallet address, currency, and I couldn't find a way to add it there. This will also close #84.
3. Third PR. We need a command like `confirm_payments` to automatically verify if the refund transaction succeeded. 

How does it look? Open for suggestions, @ligi @pipermerriam

**Comment by pipermerriam** [comment]
@ayanginet plan looks good.  You can adjust your approach as you crank out the PRs.  Thanks for splitting something large up into smaller pieces.

**Comment by ligi** [comment]
Also really appreciate the split. Keep up the good work!
And can I merge #134 - Looks good to me but there is one conversation between you both unresolved
