### ISSUE TITLE
API key in code

### ISSUE THREAD

**Issue by pipermerriam** [esPass/pretix-eth-payment-plugin#14]
https://github.com/esPass/pretix-eth-payment-plugin/blob/eedcd5c562f5afb66cc761a3409f88476fdb9118/pretix_eth/payment.py#L170

**Comment by pipermerriam** [comment]
If this is not our API key this absolutely needs to be fixed before going live.  Either way it'd be better if this was a configuration value that came from the django settings.

**Comment by ligi** [comment]
is not in the code anymore - closing
