### ISSUE TITLE
ETH payment issues with only last 10 most recent transactions

### ISSUE THREAD

**Issue by pipermerriam** [esPass/pretix-eth-payment-plugin#15]
When making a payment in `ETH` this API call is executed:

https://github.com/esPass/pretix-eth-payment-plugin/blob/eedcd5c562f5afb66cc761a3409f88476fdb9118/pretix_eth/payment.py#L124

The ethplorer API imposes a limit of 10 results when using a free API key:

https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API#freekey-limits

If a user's transaction is not in the ten most recent payments then their payment will end up failing.

**Comment by pipermerriam** [comment]
This can be fixed by moving to a non-free key which shows the last 1000 transactions which is *likely* sufficient.

**Comment by pipermerriam** [comment]
Note blockscout looks fine. If appears they include up to the last 10,000

https://blockscout.com/poa/core/api_docs

**Comment by ligi** [comment]
not using blockexplorers anymore - just plain RPCs - closing
