### ISSUE TITLE
Hide question

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#157]
we use a question to track payment info - but should be hidden from the user like here:

![image](https://user-images.githubusercontent.com/111600/133545777-f5321030-450d-4935-b7b1-21af63236174.png)

**Comment by rahul-kothari** [comment]
The solution to this is to remove the method introduced in signals.py in this commit:
https://github.com/esPass/pretix-eth-payment-plugin/commit/479e2f7e641ab84ae39fd4d53d729dc548a34ac3

Seems safe to remove.
