### ISSUE TITLE
Ethplorer API rate limiting

### ISSUE THREAD

**Issue by pipermerriam** [esPass/pretix-eth-payment-plugin#16]
### What is wrong?

We are using a free API key for ethplorer:

https://github.com/esPass/pretix-eth-payment-plugin/blob/eedcd5c562f5afb66cc761a3409f88476fdb9118/pretix_eth/payment.py#L124

The rate limit for free keys is 1 request every 2 seconds:

https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API#freekey-limits

The code which makes this request has no mechanism for detecting the HTTP error that `requests` will emit resulting in the application throwing a 500 level error.

### How can we fix it?

We need to call `raise_for_status` on the response object before calling `json()` on it to emit any HTTP based errors in the 4xx and 5xx range:

https://2.python-requests.org//en/latest/api/?highlight=raise_for_status#requests.Response.raise_for_status

Then these need to be caught, and a friendly error pushed back to the user saying something like: "Server too busy, try counting to 10 and re-submitting"

**Comment by ligi** [comment]
ethplorer is not used anymore - closing
