### ISSUE TITLE
Add ability to poll more than one RPC endpoint for confirm-payments, confirm-refunds

### ISSUE THREAD

**Issue by rahul-kothari** [esPass/pretix-eth-payment-plugin#167]
This is to prevent some kind of a DoS attack affecting us.

**Comment by ligi** [comment]
This is not about a DoS - this is about not putting all trust into a single RPC provider

**Comment by rahul-kothari** [comment]
Issue mentioned here https://github.com/esPass/pretix-eth-payment-plugin/issues/4
