### ISSUE TITLE
*Any* amount of `DAI` is accepted as payment

### ISSUE THREAD

**Issue by pipermerriam** [esPass/pretix-eth-payment-plugin#17]
Currently, the code which would accept `DAI` based payments doesn't verify that the appropriate amount was sent.

https://github.com/esPass/pretix-eth-payment-plugin/blob/eedcd5c562f5afb66cc761a3409f88476fdb9118/pretix_eth/payment.py#L142-L143

With the lines above commented out, a user could send any amount of `DAI` and successfully purchase a ticket.

**Comment by ligi** [comment]
This is not the case anymore
