### ISSUE TITLE
Orders in ETH are not finalized

### ISSUE THREAD

**Issue by jpitts** [esPass/pretix-eth-payment-plugin#19]
This is to confirm that orders in ETH are not finalized, and persist in "pending". This is tested with eth-payment-plugin 1.0.1.

Order ID: G0DDF
Ethereum Address: 0xf355ad58e038d779731d9df833694b2e5d7a05b9
Txn ID: https://etherscan.io/tx/0x3d19188f6f2f2a094658540abe1a252aebd19f45172af33c2e3d1fd7cf61e7a7

![image](https://user-images.githubusercontent.com/509756/60863600-1e018480-a1d6-11e9-84df-6c188c5fe781.png)

**Comment by ligi** [comment]
confirm mechanism completely reworked - cannot reproduce anymore
