### ISSUE TITLE
Setup rollbar for aggregated logging.

### ISSUE THREAD

**Issue by pipermerriam** [esPass/pretix-eth-payment-plugin#24]
We should setup https://rollbar.com/ for aggregated logging.

**Comment by jpitts** [comment]
I will either set up rollbar, or attempt to make use of our datadog installation. It looks like datadog has ways to intelligently filter/aggregate python / django logs but we'll go with rollbar if it is too simplistic.

**Comment by jpitts** [comment]
This is in place. Is there a good practice for adding to or modifying the settings.py in a deployment without having to alter the plugin code?

**Comment by pipermerriam** [comment]
Yes, environment vairables have been my standard way of doing that in the past.

Here's a django project of mine from a few years ago that is doing this.  It uses a simple library called `env-excavator` which is just a thin wrapper around the standard library `os.environ` API for fetching environment variables.

https://github.com/Apogaea/ladder/blob/master/ladder/settings.py#L16-L18

For things like the rollbar middleware it isn't as straight forward since you want to modify the existing value...

To handle that we *could* do something like the following and define our own settings file.

```python
# in our own settings.py file
from pretix import settings as pretix_settings

for name in dir(pretix_settings):
    if name.isupper():
        globals()[name] = getattr(pretix_settings, name)
```

The code above will duplicate all of the settings from the pretix settings to the local settings file.  From there, you can define new settings however you want.  The middleware one would probable be done like this:

```python
# in our own settings.py file
from pretix import settings as pretix_settings

for name in dir(pretix_settings):
    if name.isupper():
        globals()[name] = getattr(pretix_settings, name)

MIDDLEWARE = [
    'rollbar.whatever.RollbareMiddleware',
] + pretix_settings.MIDDLEWARE
```
```

**Comment by ligi** [comment]
afaik it is setup by @jpitts - also nothing we can do in the plugin code - right?
