### ISSUE TITLE
Expiration of exchange rates for ETH to prevent shorting

### ISSUE THREAD

**Issue by pipermerriam** [esPass/pretix-eth-payment-plugin#35]
### What was wrong?

Alice loads the order page when ETH is worth $100 each.  The backend queries for the proper exchange rate and stores it in her session.  This determines how much ETH she must pay for a ticket.

Alice now waits 12 hours, during which the price of ETH drops 10%.  She is now able to purchase a ticket at a 10% discount since the backend will use the stored exchange rate from time she loaded the order page.

### How can it be fixed?

Enforce an expiration on exchange rates for volatile currencies to ensure that there are bounds on how long someone can *short* the currency to purchase their devcon ticket.  Something like 30 minutes should be sufficient to account for network congestion or even sending funds from an exchange.

**Comment by ligi** [comment]
I think setting a exchange rate in the settings and not querying it via API is the solution here. Also makes accounting easier
