### ISSUE TITLE
Mismatch between payment_prepare and checkout_prepare

### ISSUE THREAD

**Issue by raphaelm** [esPass/pretix-eth-payment-plugin#56]
``payment_prepare`` does not call ``_get_rates_checkout``. Therefore, ``payment_ethereum_time`` and ``payment_ethereum_amount`` are not set on the session and ``execute_payment``. ``checkout_prepare`` is correct, so the bug will only occur in the "secondary" payment flow, so only if a failed payment is retried later or if a payment method is switched.

**Comment by ligi** [comment]
thanks for pointing this out!
