### ISSUE TITLE
This Checker doesn't work with contract wallets

### ISSUE THREAD

**Issue by denisgranha** [esPass/pretix-eth-payment-plugin#65]
### What was wrong?
In the code, you are checking the value with this endpoint https://blockscout.com/eth/mainnet/api?module=transaction&action=gettxinfo&txhash=0xc74c19b163b627bb3f82771efd87aa072bc996557418d08573b4f8494bf9fe28 
At this line in the code https://github.com/esPass/pretix-eth-payment-plugin/blob/master/pretix_eth/providers.py#L88

In this case, that txhash, is from a tx performed by a Gnosis Safe Wallet https://safe.gnosis.io/ 

You can see in etherscan an internal transaction https://etherscan.io/address/0x6a1517622feb74a242e68a26f423ae38e020a0b1#internaltx for Devcon tickets.

### How can it be fixed?

It needs to check the traces... not only the main value. 
* https://etherscan.io/vmtrace?txhash=0xc74c19b163b627bb3f82771efd87aa072bc996557418d08573b4f8494bf9fe28&type=parity

* https://etherscan.io/tx/0xc74c19b163b627bb3f82771efd87aa072bc996557418d08573b4f8494bf9fe28#internal

**Comment by ligi** [comment]
thanks for the report! We went for manual confirmations in DevCon5 wave1 anyway as the time ran out. So your devcon5 ticket will be confirmed soon.

The fix we will do (and use in wave2) is actually #64 as the check is then easy and the same for contract wallet tx and normal tx. We just need to check the balance of the receiving account
