### ISSUE TITLE
Error blocking users from being able to get to their order page to pay

### ISSUE THREAD

**Issue by jpitts** [esPass/pretix-eth-payment-plugin#76]
I cannot paste the error info here as it contains user-revealing info. However this error affects several users.

> KeyError at ..URL..  
> 'currency_type'
> 

Zendesk Case: 4525

Rollbar: https://rollbar.com/ethereum/Devcon5-pretix-Production/items/4/

**Comment by davesque** [comment]
Duplicate of #68.  Issue was fix in #73.
