### ISSUE TITLE
Convert wei to ETH in manual ETH payment

### ISSUE THREAD

**Issue by john-light** [esPass/pretix-eth-payment-plugin#78]
I used this checkout to buy Devcon5 tickets and when presented with an option to pay to an Ethereum address, the amount shown was in wei rather than ETH. Most wallets default to ETH, or even only allow sending in ETH denominations, and so I request that the amount shown on the checkout page also be converted from wei to ETH for ease of use.

**Comment by ligi** [comment]
using of WEI was deliberate - as people must not round their value. Doing it manually should only be done by experts - and those should know how to handle WEI. Most users should use Web3Connect anyway. The other option is just a fallback. I would signal to not change it. But keeping this issue open for other opinions.

**Comment by john-light** [comment]
> @ligi  
> using of WEI was deliberate - as people must not round their value.

Converting from wei to ETH is not the same as rounding though. For example the page asked me to send 9574470000000001086 wei which converts to 9.574470000000001086 ETH. No rounding, just a shifting of the decimal place.

**Comment by ligi** [comment]
yes - but converting it to ETH increases the probability users round. It also increases the probability that users use this option that do not know what they are doing (we already have those - we don't want more)

**Comment by john-light** [comment]
>  Doing it manually should only be done by experts - and those should know how to handle WEI. Most users should use Web3Connect anyway.

What about MyCrypto users? Or people paying from an Aragon organization? Neither supports Web3Connect and both only support sending ether denominated in ETH. Showing the amount to pay in wei when most wallets use ETH as the denomination is like uploading the source code of your app in binary. It's technically correct but like.... really?

**Comment by ligi** [comment]
yes there is data - just have a look at: 

https://etherscan.io/address/0x6A1517622feB74A242e68a26F423aE38E020a0b1

I was also very surprised...

**Comment by ligi** [comment]
also: I would love to make it easier for aragon and myCrypto users. But I think this suggestion has too many drawbacks and will increase the support-effort which is high already. Perhaps we can think about doing it after #74 #75 But I would rather love to see e.g. aragon to support Web3Connect or some other interface that allows to not have this manual process that brings PEBCAC issues

**Comment by john-light** [comment]
I'm not sure that users incorrectly rounding _even when the amount is currently shown in wei_ is evidence that they would be _more likely_ to round if the amount was shown in ETH. If the block explorer link above is showing that people are rounding when they shouldn't be then that does point to a possible UX or copywriting issue but I wouldn't use that as evidence against denominating payments in ETH when they are currently denominated in wei. If anything, it is opening the opportunity for failure because users might copy the wei amount, try to convert to ETH, and mistakenly round it in the process.

**Comment by ligi** [comment]
perhaps we should do an A/B test on this. But I am not sure we have the resources for this this year. Thinking is that using WEI increases the barrier - so people that do not know what WEI is (like non experts) do not try this. We need to only have people using this option that know what they are doing. Currently already people that do not know what they are doing seem to see themselves as "expert". I really think just doing the change as you mention would increase the amount PEBCAC

**Comment by ligi** [comment]
closing as #64 is solving it - there will be no more order encoding in the value
