### ISSUE TITLE
Automatic confirmations

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#79]
All automatic confirmation code was removed for security reasons in #49 to be able to run the first 2 waves. But as now in wave2 the dust settled and the current system seems to be stable enough so we can add complexity again. Here an outline on how to get automatic confirmations going.
The following plan:
 * plugin queries blockscout and perhaps etherscan for all transactions for the configured incoming address - it needs to do it for 3 transaction types: normal transactions, internal transactions and token transactions
 * then the plugin validates these transactions via e.g. infura RPC
 * then the plugin matches the transactions to orders
 * then the plugin marks the matching orders as paid

This should already remove most of the current manual work. After this we can get #74 and #75 going to care for the orders with user errors. 

For better and intense testing I suggest we do #5 before

**Comment by carver** [comment]
> * plugin queries blockscout and perhaps etherscan for all transactions for the configured incoming address - it needs to do it for 3 transaction types: normal transactions, internal transactions and token transactions
> * then the plugin validates these transactions via e.g. infura RPC

I hope a medium-run goal is to run our own node. :) In some ways, it may even be easier than having to reverify the results across different services.

**Comment by ligi** [comment]
I rather think the medium goal is to use a service like INCUBED or some other minimal verification client or light client - I do not think running a node just for this single task is a good idea. Also do not think ops would like the idea (cc @jpitts ) - just adds more complexity/costs/.. with no real reason.
