### ISSUE TITLE
Handle WalletConnect being on the wrong chain

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#83]
Currently when the pretix wallet is on the wrong chain - the UX is quite bad
Ideally when the wallet is on the wrong chain -> the user should be asked to switch the chain

**Comment by pedrouid** [comment]
Good point, I will fix this 👍

**Comment by ligi** [comment]
upstream issue here: https://github.com/Web3Modal/web3modal-checkout/issues/8

**Comment by rahul-kothari** [comment]
https://github.com/Web3Modal/web3modal-checkout/pull/24/commits
Fixed here
