### ISSUE TITLE
Improve payment screen UX

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#85]
![Selection_358](https://user-images.githubusercontent.com/111600/75362989-c7a69a80-58b9-11ea-84eb-35abf068ee65.png)

It will already be better after #64 as we do not need these weird sums or mentioning the whole "exactly" thing
But perhaps hiding the QR-Code and refreshing the link with a Web3Connec/WalletConnect logo could be nice

**Comment by pauljickling** [comment]
I think we can close this issue, there is a duplicate one (issue #98 ) that we are using to track.

**Comment by ligi** [comment]
ack
