### ISSUE TITLE
Update web3connect

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#86]
currently our web3connect option offers walletconnect and metamask as options.
The new web3connect version offers more options - so we should update web3connect

**Comment by pedrouid** [comment]
Which options do we want to include? There are a few of them but the modal UI is not really suitable for more than 6 providers.

We already have two with injected providers and WalletConnect, we can add another 4..

**Comment by pedrouid** [comment]
I've updated the website with web3modal and added new providers. Currently being deployed at https://checkout.web3modal.com

**Comment by pedrouid** [comment]
We should also improve the URL parameters

**Comment by pedrouid** [comment]
I would like to update currency_type to token_address and reference ETH as the zero address
