### ISSUE TITLE
Disable ETH plugin if there are no more adresses in the pool

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#92]
This is a follow-up of #91 
Currently if there are no more addresses in the pool we end up with a 500 - the better behavior would be to disable the plugin once there are no more addresses in the pool

**Comment by davesque** [comment]
I'll add a check for this.

**Comment by davesque** [comment]
I think this is resolved now: https://github.com/esPass/pretix-eth-payment-plugin/pull/91/commits/75c5ea3ea89dfb955688c241564e8899aad7148b

**Comment by ligi** [comment]
Thanks - just tried it and it works. 
0 addresses in the pool -> no eth payment visible
1 addresses in the pool -> eth payment selectable
