### ISSUE TITLE
web3modal should also support metamask

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#93]
for some reason MM is missing:

![Selection_409](https://user-images.githubusercontent.com/111600/79399368-76df2400-7f83-11ea-9857-1cb1bc690ced.png)

@pedrouid any idea? can this be enabled?

**Comment by pedrouid** [comment]
Unclear why this would happen, I just tested it on Brave, Chrome and Firefox but didn't see Metamask missing.

The conditions for displaying the injected provider is to verify that either `window.web3` or `window.ethereum` is present

**Comment by ligi** [comment]
cannot reproduce this anymore
