### ISSUE TITLE
WEI->ETH

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#94]
![Selection_410](https://user-images.githubusercontent.com/111600/79399434-9fffb480-7f83-11ea-9b2d-65dde17c556d.png)

now that we do not have exact amounts anymore we should display in ETH

**Comment by davesque** [comment]
This should be fixed now: https://github.com/esPass/pretix-eth-payment-plugin/pull/91/commits/0f5c35101dc87a15bb0f4246fea82921e4a1f0a9

**Comment by ligi** [comment]
Thanks - can confirm it works - closing.
![image](https://user-images.githubusercontent.com/111600/80490046-11b30780-8961-11ea-8947-dfba24193643.png)
