### ISSUE TITLE
Mix € / ETH

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#96]
it should only display ETH here:
![image](https://user-images.githubusercontent.com/111600/80490217-52ab1c00-8961-11ea-9a79-dc4e9fbc9c2b.png)

otherwise people might convert with their own exchange rate and this might not match ours and orders would not be confirmed. This would then end up in support hassle

**Comment by davesque** [comment]
Now that I'm looking into this, it appears that we actually have no control over what content is rendered in that part of the page from within the plugin.  I think the only way to customize this would be to create a custom fork of the entire pretix site.  For the actual location of this text, see here:
https://github.com/pretix/pretix/blob/556c77a54bfbfaf53e9826dc972b73ceb77308c8/src/pretix/presale/templates/pretixpresale/event/order.html#L66-L71

The place where our plugin content is rendered is here:
https://github.com/pretix/pretix/blob/556c77a54bfbfaf53e9826dc972b73ceb77308c8/src/pretix/presale/views/order.py#L218

That's in a completely different context from the text we want to modify.

**Comment by ligi** [comment]
I asked pretix support - and this was the answer:
```

no need to fork pretix, you can just override the template in question by placing your own file in
DATA_DIR/templates/pretixpresale/event/order.html

That said, replacing templates is not recommended since it is known to cause issues when you're not careful during updates, so do on your own risk ;)
```
