### ISSUE TITLE
adding addresses should trigger event log

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#97]
it is important to see in the event log when addresses where added

**Comment by davesque** [comment]
Sure, let's add it.  Although where are you viewing this event log?

**Comment by ligi** [comment]
This is the log I am talking about
![Selection_475](https://user-images.githubusercontent.com/111600/80774156-7b4b3580-8b5c-11ea-8b34-b8c99d8af65e.png)
you see it on the bottom of: control/event

**Comment by davesque** [comment]
Alright, I think we're good with this now: https://github.com/esPass/pretix-eth-payment-plugin/pull/91/commits/9f4d05ec7b373232cabf6539764f8a9a5901708f

**Comment by rahul-kothari** [comment]
![image](https://user-images.githubusercontent.com/35169918/134818789-97e7f310-00fe-4283-b0b7-7dd78b867dab.png)

Double confirming that this works - issue can be closed.
