### ISSUE TITLE
improve ETH payment UX

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#98]
currently it looks like this:

![image](https://user-images.githubusercontent.com/111600/80492785-cbf83e00-8964-11ea-9227-3dc26d3563f1.png)

perhaps we can use icons for web3modal and uniswap to break the wall of text. Also perhaps not show the big QR code by default but a small QR code Icon and reveal the bigger one after click.

We can also remove the "once a day" as we now check more often. Also maybe the warning "if you know what you are doing" as we do not need the exact amounts anymore.

**Comment by skylarweaver** [comment]
In addition to the suggestions Ligi made, can we make the following text changes:

**Change** the 0.01 euros at the top to dollars or DAI or ETH, whichever one it actually is...?

**Remove**: "Please send your ticket payment ... below."

**Change**: "You have the following options to trigger the payment:" **to** "Choose one of the following options to send the payment:"

**Convert** the unordered list to an ordered (numbered) list. (this way it's easy for people to reference, "oh you should pay with option #2", etc)

**Change**: "If you already paid, please be patient!  Transactions are currently checked just once a day.  Once this happens, you will get an email" **to** "Once you send your payment, our system will automatically check for confirmation. Please allow up to several hours. Once confirmed, you will get an email notification."

Is several hours too long to wait? What's the shortest amount of time we should say they should wait before reaching out to support b/c something is likely wrong? 10 minutes?  

Also, do they still receive the confirmation email?

**Add**: A line break before the text "If you want to improve this process, submit..."

**Comment by skylarweaver** [comment]
Those are all basic html/text changes. Should be easy enough to start. With those, we can start testing MVP IMO.

As for CSS, the biggest changes I would like to see would be to change the Web3Modal and Uniswap hyperlinks into styled buttons:

- Text can be the same "Via [Web3Modal/Uniswap]".
- Color should match their respective brands
- Icon should be respective: [web3modal](https://web3connect.com/static/media/web3modal-logo.25fffe10.png) and Uniswap's is an SVG [on their site](https://uniswap.org/)
- Placement can be the same (inside the ordered list, next to their respective number, with supporting text below as mentioned in the above comment).
- 

A secondary change would be to give them address in manual payment a light, neutral background, so it stands out as selectable/copyable.

Are these CSS changes possible to implement in addition to the above html/text changes?

**Comment by davesque** [comment]
I addressed most of the textual changes that are possible to fix.  The currency display issue probably is not fixable unfortunately.  See my comment [here](https://github.com/esPass/pretix-eth-payment-plugin/issues/96#issuecomment-623256537).  As for everything else, I'm pretty sure a front-end engineer can address it.  I'm going to need to start pulling back the time I'm putting into this project since my day job is becoming more demanding.

**Comment by skylarweaver** [comment]
Terrific. Thanks for all the help @davesque ! Is there a branch or a PR with these changes?

**Comment by davesque** [comment]
Yeah, it's here: https://github.com/esPass/pretix-eth-payment-plugin/pull/91

Just look at that last few commits.
