### ISSUE TITLE
ChildNodes error from question-type.js on Your Cart page (before Checkout)

### ISSUE THREAD

**Issue by skylarweaver** [esPass/pretix-eth-payment-plugin#99]
* OS: osx
* Chrome

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
question-type.js

* The full output of the error
![image](https://user-images.githubusercontent.com/4008777/80910871-70460000-8d2a-11ea-8fca-cd37eead5478.png)
Uncaught TypeError: Cannot read property 'childNodes' of null
    at HTMLDocument.<anonymous> (question-type.f9093b8bd9ac.js:94)
    at j (output.de09cebf3454.js:1)
    at Object.fireWith [as resolveWith] (output.de09cebf3454.js:1)
    at Function.ready (output.de09cebf3454.js:1)
    at HTMLDocument.I (output.de09cebf3454.js:1)

**Comment by ligi** [comment]
@pauljickling can you have a look at this one?

**Comment by skylarweaver** [comment]
New error:
![image](https://user-images.githubusercontent.com/4008777/81824757-d5a4a880-9503-11ea-9378-ca723ff182e7.png)


Uncaught TypeError: Cannot read property 'parentNode' of null
    at HTMLDocument.<anonymous> (question-type.7c0cd425e725.js:236)
    at j (output.de09cebf3454.js:1)
    at Object.fireWith [as resolveWith] (output.de09cebf3454.js:1)
    at Function.ready (output.de09cebf3454.js:1)
    at HTMLDocument.I (output.de09cebf3454.js:1)

**Comment by pauljickling** [comment]
So good news/bad news.

Good news: This error is logically easy to understand, and handle.

Bad news: Very annoyingly, this error message is not appearing in my local environment. So while I can write a bit of code that handles this case that makes sense, I can't verify that the solution correctly handles the error message.

**Comment by skylarweaver** [comment]
Maybe first try to get the error to replicate in your local? Or is there a
known reason why it’s not?

**Comment by pauljickling** [comment]
Actually I am having trouble generating this error message on staging as well. On Chrome (OS Catalina) my console looks like this (even with verbose log  levels):

<img width="1390" alt="Screen Shot 2020-05-13 at 9 58 43 AM" src="https://user-images.githubusercontent.com/18646852/81842279-9a54aa80-9500-11ea-85a3-58bc0d10a82e.png">

I also cleared cache just to make sure I wasn't loading old JS.

**Comment by pauljickling** [comment]
@ligi @kvbik can you both check to see if you are seeing this error message in your console on staging? It is not appearing in the console for me when I try to generate it. It should appear on the cart page.

**Comment by pauljickling** [comment]
I investigated this error on the latest staging server, but haven't seen it crop up. I recommend closing the issue unless it can be replicated again.
